### ISSUE TITLE
Error while setting up bitvavo platform for sensor

### ISSUE THREAD

**Issue by Cornmeister** [cyberjunky/home-assistant-bitvavo#1]
When I try to start this component, the log provides me the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bitvavo/sensor.py", line 34, in async_setup_entry
    entities.append(Balance(coordinator, balance))
  File "/config/custom_components/bitvavo/sensor.py", line 111, in __init__
    self._icon = CURRENCY_ICONS.get(self.unit_of_measurement, DEFAULT_COIN_ICON)
  File "/config/custom_components/bitvavo/sensor.py", line 139, in unit_of_measurement
    return self._unit_of_measurement
AttributeError: 'Balance' object has no attribute '_unit_of_measurement'

I created an API key at bitvavo site, and enabled the account info option. other options are disabled.
Any idea what goes wrong ?

**Comment by cyberjunky** [comment]
It was a bug, this repo is not always uptodate with the PR in homeassistant/core (which is still updated), I have synced it now, can you try?

**Comment by Cornmeister** [comment]
same error, updated HA docker to latest stable, removed component from HACS, and reinstalled.

**Comment by cyberjunky** [comment]
Because you run the same code, I didn't release new version, but the code files are.

**Comment by cyberjunky** [comment]
I now have created 1.0.1 so you don't need to copy them the files from the repo

**Comment by Cornmeister** [comment]
Awesome ! works fine now !

many thanks
